# Running Checks

In [2]:
%load_ext autoreload
%autoreload 2
%cd /mnt/c/Users/resha/Documents/Github/balancing_framework/

from gluonts.dataset.repository import get_dataset, dataset_names
from gluonts.dataset.util import to_pandas

import pickle
import pandas as pd
import numpy as np
import json
import time
import argparse
from tqdm import tqdm

from framework import run_measurements, viz
from fracdiff import frac_diff_bestd
from monash_data_utils import convert_tsf_to_dataframe, monash_df_to_gluonts_train_datasets
import os

from statsmodels.tsa.stattools import adfuller

def run_adf(series):
    adf_chunk_size = 100_000
    num_stat = (0,0) # number of stationary windows, total number of windows
    p_values = []
    for i in range(0, len(series), adf_chunk_size):
        data_chunk = series.dropna()[i:i+adf_chunk_size]
        if data_chunk.nunique()==1:
            print(f'series has only one unique value: {series.iloc[0]}')
            continue
        try:
            adf_result = adfuller(data_chunk) 
        except Exception as e:
            print(e)
            continue
        # print(f'{i} p-value={adf_result[1]}, lags={adf_result[2]}')
        num_stat = (num_stat[0], num_stat[1]+1)
        p_values.append(adf_result[1])
        if adf_result[1] < 0.05:
            num_stat = (num_stat[0]+1, num_stat[1])
    # if more than 50% of the p-values are above 0.05, then the data is not stationary
    stationary = num_stat[0] >= num_stat[1]/2
    return stationary

/mnt/c/Users/resha/Documents/Github/balancing_framework

/home/reshawn/miniconda3/envs/clfr/lib/python3.11/site-packages/gluonts/json.py:102: UserWarning: Using `json`-module for json-handling. Consider installing one of `orjson`, `ujson` to speed up serialization and deserialization.
  warnings.warn(

In [ ]:
# Loop through monash dir


monash_dir = "monash_data"
results = pd.DataFrame()
for dataset_name in tqdm(os.listdir(monash_dir)):
    print(dataset_name)
    loaded_data, frequency, forecast_horizon, contain_missing_values, contain_equal_length = convert_tsf_to_dataframe(f"{monash_dir}/{dataset_name}")
    dataset = monash_df_to_gluonts_train_datasets(loaded_data, frequency)
    series_lengths = []
    num_stat = 0

    for entry in tqdm(dataset.test):
        row = pd.Series(entry['target'])
        series_lengths.append(len(row))
        stat = run_adf(row)
        if stat: num_stat += 1
    
    results = pd.concat([results, pd.DataFrame([{
        'dataset_name': dataset_name,
        'num_series': len(dataset.test),
        'num_stat': num_stat,
        'pct_stat': num_stat/len(dataset.test),
        'mean_series_len': np.mean(series_lengths),
        'std_series_len': np.std(series_lengths),
        'min_series_len': np.min(series_lengths),
        'max_series_len': np.max(series_lengths),
    }])], ignore_index=True)
    results.to_csv('results_stat_checks.csv')
    

results

In [ ]:
results = pd.read_csv('results_stat_checks.csv', index_col=0)
results.sort_values(['pct_stat'], ascending=True)

,dataset_name,num_series,num_stat,pct_stat,mean_series_len,std_series_len,min_series_len,max_series_len
41,tourism_monthly_dataset.tsf,366,3,0.008197,2.985792e+02,55.575410,91,333
42,tourism_quarterly_dataset.tsf,427,4,0.009368,9.963466e+01,20.312835,30,130
36,solar_weekly_dataset.tsf,137,5,0.036496,5.200000e+01,0.000000,52,52
21,m4_daily_dataset.tsf,4227,195,0.046132,2.371383e+03,1756.361126,107,9933
5,cif_2016_dataset.tsf,72,4,0.055556,9.872222e+01,31.639560,28,120
16,m1_quarterly_dataset.tsf,203,14,0.068966,4.898522e+01,16.870261,18,114
19,m3_quarterly_dataset.tsf,756,61,0.080688,4.894709e+01,10.628396,24,72
43,tourism_yearly_dataset.tsf,518,46,0.088803,2.462741e+01,5.331318,11,47
24,m4_quarterly_dataset.tsf,24000,2198,0.091583,1.002545e+02,51.128442,24,874
26,m4_yearly_dataset.tsf,23000,2116,0.092000,3.732426e+01,24.523433,19,841
17,m1_yearly_dataset.tsf,181,22,0.121547,2.494475e+01,8.753672,15,58
23,m4_monthly_dataset.tsf,48000,6076,0.126583,2.343002e+02,137.404864,60,2812
10,fred_md_dataset.tsf,107,14,0.130841,7.280000e+02,0.000000,728,728
15,m1_monthly_dataset.tsf,617,84,0.136143,9.075851e+01,28.672550,48,150
31,rideshare_dataset_without_missing_values.tsf,2304,368,0.159722,5.410000e+02,0.000000,541,541
20,m3_yearly_dataset.tsf,645,105,0.162791,2.840155e+01,9.890485,20,47
18,m3_monthly_dataset.tsf,1428,322,0.225490,1.173403e+02,28.498570,66,144
6,covid_deaths_dataset.tsf,266,60,0.225564,2.120000e+02,0.000000,212,212
25,m4_weekly_dataset.tsf,359,84,0.233983,1.035039e+03,706.162881,93,2610
1,bitcoin_dataset_without_missing_values.tsf,18,6,0.333333,4.186889e+03,467.273759,2659,4581
2,bitcoin_dataset_with_missing_values.tsf,18,6,0.333333,4.581000e+03,0.000000,4581,4581
47,vehicle_trips_dataset_without_missing_values.tsf,329,124,0.376900,1.288207e+02,39.560827,70,243
22,m4_hourly_dataset.tsf,414,181,0.437198,9.018647e+02,127.790745,748,1008
11,hospital_dataset.tsf,767,370,0.482399,8.400000e+01,0.000000,84,84
48,vehicle_trips_dataset_with_missing_values.tsf,329,169,0.513678,1.288207e+02,39.560827,70,243
45,traffic_weekly_dataset.tsf,862,476,0.552204,1.040000e+02,0.000000,104,104
9,electricity_weekly_dataset.tsf,321,186,0.579439,1.560000e+02,0.000000,156,156
7,dominick_dataset.tsf,115704,71704,0.619719,1.650158e+02,105.513683,28,393
29,nn5_weekly_dataset.tsf,111,85,0.765766,1.130000e+02,0.000000,113,113
4,car_parts_dataset_with_missing_values.tsf,2674,2089,0.781227,5.100000e+01,0.000000,51,51
3,car_parts_dataset_without_missing_values.tsf,2674,2145,0.802169,5.100000e+01,0.000000,51,51
12,kaggle_web_traffic_weekly_dataset.tsf,145063,117560,0.810407,1.140000e+02,0.000000,114,114
28,nn5_daily_dataset_with_missing_values.tsf,111,98,0.882883,7.910000e+02,0.000000,791,791
27,nn5_daily_dataset_without_missing_values.tsf,111,98,0.882883,7.910000e+02,0.000000,791,791
40,temperature_rain_dataset_with_missing_values.tsf,32072,29619,0.923516,7.250000e+02,0.000000,725,725
39,temperature_rain_dataset_without_missing_value...,32072,29790,0.928848,7.250000e+02,0.000000,725,725
32,rideshare_dataset_with_missing_values.tsf,2304,2189,0.950087,5.410000e+02,0.000000,541,541
8,electricity_hourly_dataset.tsf,321,315,0.981308,2.630400e+04,0.000000,26304,26304
30,pedestrian_counts_dataset.tsf,66,65,0.984848,4.745979e+04,30762.855175,576,96424
49,weather_dataset.tsf,3010,2977,0.989037,1.429635e+04,11097.638867,1332,65981
44,traffic_hourly_dataset.tsf,862,862,1.000000,1.754400e+04,0.000000,17544,17544
46,us_births_dataset.tsf,1,1,1.000000,7.305000e+03,0.000000,7305,7305
0,australian_electricity_demand_dataset.tsf,5,5,1.000000,2.310528e+05,609.883399,230736,232272
37,sunspot_dataset_without_missing_values.tsf,1,1,1.000000,7.392400e+04,0.000000,73924,73924
35,solar_4_seconds_dataset.tsf,1,1,1.000000,7.397222e+06,0.000000,7397222,7397222
34,solar_10_minutes_dataset.tsf,137,137,1.000000,5.256000e+04,0.000000,52560,52560
33,saugeenday_dataset.tsf,1,1,1.000000,2.374100e+04,0.000000,23741,23741
14,kdd_cup_2018_dataset_with_missing_values.tsf,270,270,1.000000,1.089764e+04,85.456462,9504,10920
13,kdd_cup_2018_dataset_without_missing_values.tsf,270,270,1.000000,1.089764e+04,85.456462,9504,10920
38,sunspot_dataset_with_missing_values.tsf,1,1,1.000000,7.392400e+04,0.000000,73924,73924
50,wind_4_seconds_dataset.tsf,1,1,1.000000,7.397147e+06,0.000000,7397147,7397147

In [ ]:
datasets = []
for dataset_name in dataset_names:
    try:
        datasets.append(get_dataset(dataset_name))
    except Exception as e:
        print(e)
        pass

[Errno 2] No such file or directory: '/home/reshawn/.gluonts/datasets/wind_farms_without_missing/metadata.json'

Download car_parts_dataset_without_missing_values.zip:: 40.0kB [00:02, 20.1kB/s]
creating json files: 100%|██████████| 2674/2674 [00:00<00:00, 140853.10it/s]
Download dominick_dataset.zip:: 11.8MB [00:33, 367kB/s]
creating json files: 100%|██████████| 115704/115704 [00:01<00:00, 104559.16it/s]
Download fred_md_dataset.zip:: 168kB [00:01, 113kB/s]
creating json files: 100%|██████████| 107/107 [00:00<00:00, 149397.65it/s]
Download pedestrian_counts_dataset.zip:: 4.38MB [00:16, 280kB/s]
creating json files: 100%|██████████| 66/66 [00:00<00:00, 131883.78it/s]
Download hospital_dataset.zip:: 80.0kB [00:01, 47.0kB/s]
creating json files: 100%|██████████| 767/767 [00:00<00:00, 174440.47it/s]
Download covid_deaths_dataset.zip:: 32.0kB [00:01, 23.7kB/s]
creating json files: 100%|██████████| 266/266 [00:00<00:00, 146396.12it/s]
Download kdd_cup_2018_dataset_without_missing_values.zip:: 2.32MB [00:06, 354kB/s]
creating json files: 100%|██████████| 270/270 [00:00<00:00, 152089.99it/s]
Download weather_dataset.zip:: 37.0MB [01:24, 458kB/s]
creating json files: 100%|██████████| 3010/3010 [00:00<00:00, 349854.65it/s]

The m3 data is available at https://forecasters.org/resources/time-series-data/m3-competition/ Please download the file and copy the files to this location: /home/reshawn/.gluonts/datasets/M3C.xls
The m3 data is available at https://forecasters.org/resources/time-series-data/m3-competition/ Please download the file and copy the files to this location: /home/reshawn/.gluonts/datasets/M3C.xls
The m3 data is available at https://forecasters.org/resources/time-series-data/m3-competition/ Please download the file and copy the files to this location: /home/reshawn/.gluonts/datasets/M3C.xls
The m3 data is available at https://forecasters.org/resources/time-series-data/m3-competition/ Please download the file and copy the files to this location: /home/reshawn/.gluonts/datasets/M3C.xls
M5 data is available on Kaggle (https://www.kaggle.com/c/m5-forecasting-accuracy/data). You first need to agree to the terms of the competition before being able to download the data. After you have done that, please supply the files at /home/reshawn/.gluonts/m5.

Download australian_electricity_demand_dataset.zip:: 5.51MB [00:14, 396kB/s]
creating json files: 100%|██████████| 5/5 [00:00<00:00, 29289.83it/s]
Download electricity_hourly_dataset.zip:: 11.3MB [00:20, 577kB/s]
creating json files: 100%|██████████| 321/321 [00:00<00:00, 133489.15it/s]
Download electricity_weekly_dataset.zip:: 152kB [00:01, 106kB/s]
creating json files: 100%|██████████| 321/321 [00:00<00:00, 142820.79it/s]
Download rideshare_dataset_without_missing_values.zip:: 1.03MB [00:02, 372kB/s]
creating json files: 100%|██████████| 2304/2304 [00:00<00:00, 8530.86it/s]

[Errno 2] No such file or directory: '/home/reshawn/.gluonts/datasets/saugeenday/metadata.json'
[Errno 2] No such file or directory: '/home/reshawn/.gluonts/datasets/solar_10_minutes/metadata.json'

Download temperature_rain_dataset_without_missing_values.zip:: 24.0MB [00:39, 633kB/s]
creating json files: 100%|██████████| 32072/32072 [00:00<00:00, 76236.04it/s]
Download vehicle_trips_dataset_without_missing_values.zip:: 48.0kB [00:01, 42.3kB/s]
creating json files: 100%|██████████| 329/329 [00:00<00:00, 149020.09it/s]

In [ ]:
#
results = pd.DataFrame()
for dataset_name in tqdm(dataset_names):
    try:
        dataset = get_dataset(dataset_name)
        print(dataset_name)
    except Exception as e:
        print(e)
        continue
    series_lengths = []
    num_stat = 0

    for entry in dataset.test:
        row = pd.Series(entry['target'])
        series_lengths.append(len(row))
        stat = run_adf(row)
        if stat: num_stat += 1
    
    results = pd.concat([results, pd.DataFrame([{
        'dataset_name': dataset_name,
        'num_series': len(dataset.test),
        'num_stat': num_stat,
        'pct_stat': num_stat/len(dataset.test),
        'mean_series_len': np.mean(series_lengths),
        'std_series_len': np.std(series_lengths),
        'min_series_len': np.min(series_lengths),
        'max_series_len': np.max(series_lengths),
    }])], ignore_index=True)
    results.to_csv('results_stat_checks_gluonts.csv')
    

results

In [18]:
results = pd.read_csv('results_stat_checks_gluonts.csv', index_col=0)  # results_stat_checks
results['mean_series_len'] = np.round(results['mean_series_len'], 3)
results['std_series_len'] = np.round(results['std_series_len'], 3)

In [19]:
series_len = []
for i, row in results.iterrows():
    lenstring = f'{row["mean_series_len"]} ± {row["std_series_len"]}'
    series_len.append(lenstring)

results['mean_series_len_string'] = series_len
results

,dataset_name,num_series,num_stat,pct_stat,mean_series_len,std_series_len,min_series_len,max_series_len,pct_nonstat,mean_series_len_string
0,constant,10,10,1.000000,30.000,0.000,30,30,0.000000,30.0 ± 0.0
1,exchange_rate,40,0,0.000000,6161.000,42.426,6101,6221,1.000000,6161.0 ± 42.426
2,solar-energy,959,959,1.000000,7105.000,48.000,7033,7177,0.000000,7105.0 ± 48.0
3,electricity,2247,2177,0.968847,21140.000,48.000,21068,21212,0.031153,21140.0 ± 48.0
4,traffic,6034,6034,1.000000,14132.000,48.000,14060,14204,0.000000,14132.0 ± 48.0
5,exchange_rate_nips,40,0,0.000000,6161.000,42.426,6101,6221,1.000000,6161.0 ± 42.426
6,electricity_nips,2590,2179,0.841313,3992.370,146.584,1105,4000,0.158687,3992.37 ± 146.584
7,traffic_nips,6741,6628,0.983237,4000.000,0.000,4000,4000,0.016763,4000.0 ± 0.0
8,solar_nips,959,959,1.000000,7105.000,48.000,7033,7177,0.000000,7105.0 ± 48.0
9,wiki2000_nips,10000,7107,0.710700,852.000,42.426,792,912,0.289300,852.0 ± 42.426
10,wiki-rolling_nips,47675,34047,0.714148,852.000,42.426,792,912,0.285852,852.0 ± 42.426
11,taxi_30min,67984,67678,0.995499,809.000,387.918,149,1469,0.004501,809.0 ± 387.918
12,kaggle_web_traffic_with_missing,145063,127847,0.881321,803.000,0.000,803,803,0.118679,803.0 ± 0.0
13,kaggle_web_traffic_without_missing,145063,127379,0.878094,803.000,0.000,803,803,0.121906,803.0 ± 0.0
14,kaggle_web_traffic_weekly,145063,117560,0.810407,114.000,0.000,114,114,0.189593,114.0 ± 0.0
15,m1_yearly,181,22,0.121547,24.945,8.754,15,58,0.878453,24.945 ± 8.754
16,m1_quarterly,203,14,0.068966,48.985,16.870,18,114,0.931034,48.985 ± 16.87
17,m1_monthly,617,84,0.136143,90.759,28.673,48,150,0.863857,90.759 ± 28.673
18,nn5_daily_with_missing,111,98,0.882883,791.000,0.000,791,791,0.117117,791.0 ± 0.0
19,nn5_daily_without_missing,111,98,0.882883,791.000,0.000,791,791,0.117117,791.0 ± 0.0
20,nn5_weekly,111,85,0.765766,113.000,0.000,113,113,0.234234,113.0 ± 0.0
21,tourism_monthly,366,3,0.008197,298.579,55.575,91,333,0.991803,298.579 ± 55.575
22,tourism_quarterly,427,4,0.009368,99.635,20.313,30,130,0.990632,99.635 ± 20.313
23,tourism_yearly,518,46,0.088803,24.627,5.331,11,47,0.911197,24.627 ± 5.331
24,cif_2016,72,4,0.055556,98.722,31.640,28,120,0.944444,98.722 ± 31.64
25,london_smart_meters_without_missing,5560,5544,0.997122,29951.240,5262.991,288,39648,0.002878,29951.24 ± 5262.991
26,car_parts_without_missing,2674,2145,0.802169,51.000,0.000,51,51,0.197831,51.0 ± 0.0
27,dominick,115704,71704,0.619719,165.016,105.514,28,393,0.380281,165.016 ± 105.514
28,fred_md,107,14,0.130841,728.000,0.000,728,728,0.869159,728.0 ± 0.0
29,pedestrian_counts,66,65,0.984848,47459.788,30762.855,576,96424,0.015152,47459.788 ± 30762.855
30,hospital,767,370,0.482399,84.000,0.000,84,84,0.517601,84.0 ± 0.0
31,covid_deaths,266,60,0.225564,212.000,0.000,212,212,0.774436,212.0 ± 0.0
32,kdd_cup_2018_without_missing,270,270,1.000000,10897.644,85.456,9504,10920,0.000000,10897.644 ± 85.456
33,weather,3010,2977,0.989037,14296.346,11097.639,1332,65981,0.010963,14296.346 ± 11097.639
34,m4_hourly,414,181,0.437198,901.865,127.791,748,1008,0.562802,901.865 ± 127.791
35,m4_daily,4227,195,0.046132,2371.383,1756.361,107,9933,0.953868,2371.383 ± 1756.361
36,m4_weekly,359,84,0.233983,1035.039,706.163,93,2610,0.766017,1035.039 ± 706.163
37,m4_monthly,48000,6076,0.126583,234.300,137.405,60,2812,0.873417,234.3 ± 137.405
38,m4_quarterly,24000,2198,0.091583,100.254,51.128,24,874,0.908417,100.254 ± 51.128
39,m4_yearly,22974,2111,0.091886,36.785,17.561,19,284,0.908114,36.785 ± 17.561
40,uber_tlc_daily,262,25,0.095420,179.721,8.231,110,181,0.904580,179.721 ± 8.231
41,uber_tlc_hourly,262,262,1.000000,4310.855,200.616,2626,4344,0.000000,4310.855 ± 200.616
42,airpassengers,1,0,0.000000,144.000,0.000,144,144,1.000000,144.0 ± 0.0
43,australian_electricity_demand,5,5,1.000000,231052.800,609.883,230736,232272,0.000000,231052.8 ± 609.883
44,electricity_hourly,321,315,0.981308,26304.000,0.000,26304,26304,0.018692,26304.0 ± 0.0
45,electricity_weekly,321,186,0.579439,156.000,0.000,156,156,0.420561,156.0 ± 0.0
46,rideshare_without_missing,2304,368,0.159722,541.000,0.000,541,541,0.840278,541.0 ± 0.0
47,solar_weekly,137,5,0.036496,52.000,0.000,52,52,0.963504,52.0 ± 0.0
48,sunspot_without_missing,1,1,1.000000,73924.000,0.000,73924,73924,0.000000,73924.0 ± 0.0
49,temperature_rain_without_missing,32072,29790,0.928848,725.000,0.000,725,725,0.071152,725.0 ± 0.0
50,vehicle_trips_without_missing,329,124,0.376900,128.821,39.561,70,243,0.623100,128.821 ± 39.561
51,ercot,8,8,1.000000,154854.000,0.000,154854,154854,0.000000,154854.0 ± 0.0
52,ett_small_15min,14,14,1.000000,69680.000,0.000,69680,69680,0.000000,69680.0 ± 0.0
53,ett_small_1h,14,13,0.928571,17420.000,0.000,17420,17420,0.071429,17420.0 ± 0.0

# Series Selection

In [10]:
results1 = pd.read_csv('results_stat_checks.csv', index_col=0)
results2 = pd.read_csv('results_stat_checks_gluonts.csv', index_col=0)

In [12]:
results1['pct_nonstat'] = 1 - results1['pct_stat']
results2['pct_nonstat'] = 1 - results2['pct_stat']
results1.to_csv('results_stat_checks.csv')
results2.to_csv('results_stat_checks_gluonts.csv')

In [1]:
# re run checks to store more on the series 

%load_ext autoreload
%autoreload 2
%cd /mnt/c/Users/resha/Documents/Github/balancing_framework/

from gluonts.dataset.repository import get_dataset, dataset_names
from gluonts.dataset.util import to_pandas

import pickle
import pandas as pd
import numpy as np
import json
import time
import argparse
from tqdm import tqdm

from framework import run_measurements, viz
from fracdiff import frac_diff_bestd
from monash_data_utils import convert_tsf_to_dataframe, monash_df_to_gluonts_train_datasets
import os

from statsmodels.tsa.stattools import adfuller

def run_adf(series):
    adf_chunk_size = 100_000
    num_stat = (0,0) # number of stationary windows, total number of windows
    p_values = []
    for i in range(0, len(series), adf_chunk_size):
        data_chunk = series.dropna()[i:i+adf_chunk_size]
        if data_chunk.nunique()==1:
            print(f'series has only one unique value: {series.iloc[0]}')
            continue
        try:
            adf_result = adfuller(data_chunk) 
        except Exception as e:
            print(e)
            continue
        # print(f'{i} p-value={adf_result[1]}, lags={adf_result[2]}')
        num_stat = (num_stat[0], num_stat[1]+1)
        p_values.append(adf_result[1])
        if adf_result[1] < 0.05:
            num_stat = (num_stat[0]+1, num_stat[1])
    # if more than 50% of the p-values are above 0.05, then the data is not stationary
    stationary = num_stat[0] >= num_stat[1]/2
    return stationary, np.mean(p_values)

/mnt/c/Users/resha/Documents/Github/balancing_framework

/home/reshawn/miniconda3/envs/clfr/lib/python3.11/site-packages/gluonts/json.py:102: UserWarning: Using `json`-module for json-handling. Consider installing one of `orjson`, `ujson` to speed up serialization and deserialization.
  warnings.warn(

In [ ]:
# Loop through monash dir


monash_dir = "monash_data"
results = pd.DataFrame()
for dataset_name in tqdm(os.listdir(monash_dir)):
    print(dataset_name)
    loaded_data, frequency, forecast_horizon, contain_missing_values, contain_equal_length = convert_tsf_to_dataframe(f"{monash_dir}/{dataset_name}")
    dataset = monash_df_to_gluonts_train_datasets(loaded_data, frequency)

    for index, entry in tqdm(enumerate(dataset.test)):
        row = pd.Series(entry['target'])
        stat, pva = run_adf(row)
        if not stat: 
            new_row = pd.DataFrame([{
                'dataset_name': dataset_name,
                'series_idx': index,
                'avg_pvalue': pva,
                'series_length': len(row),
            }])
            new_row.to_csv('series_pick_checks.csv', mode='a', index=False)
    

results

In [ ]:
#
results = pd.DataFrame()
for dataset_name in tqdm(dataset_names):
    try:
        dataset = get_dataset(dataset_name)
        print(dataset_name)
    except Exception as e:
        print(e)
        continue

    for index, entry in enumerate(dataset.test):
        row = pd.Series(entry['target'])
        stat, pva = run_adf(row)
        if not stat: 
            new_row = pd.DataFrame([{
                'dataset_name': dataset_name,
                'series_idx': index,
                'avg_pvalue': pva,
                'series_length': len(row),
            }])
            new_row.to_csv('series_pick_checks_gluonts.csv', mode='a', index=False)
    

results

# Series Selection Results

In [2]:
%load_ext autoreload
%autoreload 2
%cd /mnt/c/Users/resha/Documents/Github/balancing_framework/

import pandas as pd
pd.set_option('display.max_rows', None)
mres = pd.read_csv('series_pick_checks.csv', header=None).rename(columns={0:'dataset_name', 1:'series_idx', 2:'avg_pvalue', 3:'series_length'})
gres = pd.read_csv('series_pick_checks_gluonts.csv', header=None).rename(columns={0:'dataset_name', 1:'series_idx', 2:'avg_pvalue', 3:'series_length'})
gres['dataset_name'] = gres['dataset_name'] + ' (g)'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/mnt/c/Users/resha/Documents/Github/balancing_framework

In [3]:
# combine
res = pd.concat([mres, gres], ignore_index=True)
print(len(res))
res.drop_duplicates(inplace=True)
print(len(res))

396433
396433

In [34]:
res.sort_values('series_length', inplace=True, ascending=False)
res.to_csv('combined_pick_checks.csv')

In [4]:
ignore = ['m4_weekly', 'm4_daily', 'm4_hourly', 'london_smart_meters_without_missing (g)', 'electricity_hourly_dataset.tsf', 'electricity_hourly (g)', 'electricity (g)', 'exchange_rate (g)', 'exchange_rate_nips (g)', 'bitcoin_dataset_with_missing_values.tsf', 'm4_daily_dataset.tsf',]

In [ ]:
res[res['series_length']>30_000].sort_values('avg_pvalue', ascending=False)

/tmp/ipykernel_1558910/2751440846.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  res[res['series_length']>30_000][~res['dataset_name'].isin(ignore)].sort_values('avg_pvalue', ascending=False)

Empty DataFrame
Columns: [dataset_name, series_idx, avg_pvalue, series_length]
Index: []

In [ ]:
res[~res['dataset_name'].isin(ignore)].sort_values('series_length', ascending=False)