In [1]:
# to reload local packages when debugging
%load_ext autoreload
%autoreload 2

%cd /mnt/c/Users/resha/Documents/Github/balancing_framework/

/mnt/c/Users/resha/Documents/Github/balancing_framework

In [2]:
import pickle
import pandas as pd
import numpy as np

with open('/mnt/c/Users/resha/Documents/Github/balancing_framework/spy5m_labelled_episodes.pkl', 'rb') as f:
    df_original = pickle.load(f)
with open('/mnt/c/Users/resha/Documents/Github/balancing_framework/spy5m_labelled_episodes_fracdiff.pkl', 'rb') as f:
    df_fd = pickle.load(f)
# PZ algorithm has some look ahead so remove the episode labels, will be uesd only for some kind of analysis afterwards
df = df_original.drop(columns=['episode']) 
# df

In [ ]:
def bin_tp_label(row, tp):
    window = df[row.name: row.name + pd.Timedelta('24h')]
    returns = (window.close / row.close) - 1
    if returns[returns > tp].shape[0] >= 1:
        return 1
    else:
        return 0
    
tp = 0.004
df[f'tp_{tp}'] = df.apply(lambda row: bin_tp_label(row, tp), axis=1)
df['tp_0.004'].value_counts()

In [69]:
import pickle

with open('spy5m_bintp_labelled.pkl', 'wb') as f:
    pickle.dump(df, f)

In [74]:
df

,volume,vwap,open,close,high,low,transactions,label,tp_0.01,tp_0.001,tp_0.005,tp_0.0075,tp_0.0025,tp_0.0035,tp_0.004
timestamp,,,,,,,,,,,,,,,
2003-09-10 08:00:00-04:00,1000.0,102.8600,102.8600,102.8600,102.8600,102.86,1,1,0,0,0,0,0,0,0
2003-09-10 08:05:00-04:00,1600.0,102.8750,102.8600,102.9000,102.9000,102.86,4,0,0,0,0,0,0,0,0
2003-09-10 08:10:00-04:00,1300.0,102.8615,102.9000,102.8500,102.9000,102.85,2,0,0,0,0,0,0,0,0
2003-09-10 08:20:00-04:00,100.0,102.8000,102.8000,102.8000,102.8000,102.80,1,0,0,0,0,0,0,0,0
2003-09-10 08:25:00-04:00,17900.0,102.7358,102.7200,102.7300,102.7700,102.72,5,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-30 19:40:00-04:00,10401.0,500.9938,500.9101,501.0682,501.0682,500.91,93,1,0,0,0,0,0,0,0
2024-04-30 19:45:00-04:00,3686.0,501.1517,501.1200,501.1500,501.1800,501.11,62,0,0,0,0,0,0,0,0
2024-04-30 19:50:00-04:00,1952.0,501.0709,501.1500,500.9900,501.1500,500.99,56,1,0,0,0,0,0,0,0
2024-04-30 19:55:00-04:00,17285.0,501.2314,501.0600,501.2800,501.3100,501.06,143,1,0,0,0,0,0,0,0
2024-04-30 20:00:00-04:00,336.0,501.3000,501.3000,501.3000,501.3000,501.30,3,0,0,0,0,0,0,0,0

In [ ]:
with open('/mnt/c/Users/resha/Documents/Github/balancing_framework/spy5m_labelled_episodes_fracdiff.pkl', 'rb') as f:
    df_fd = pickle.load(f)

df_fd['label'] = df['tp_0.004'][df_fd.index]

with open('spy5m_bintp004_episodes_fracdiff.pkl', 'wb') as f:
    pickle.dump(df_fd, f)

In [3]:
with open('/mnt/c/Users/resha/Documents/Github/balancing_framework/spy5m_bintp_labelled.pkl', 'rb') as f:
    df = pickle.load(f)
with open('/mnt/c/Users/resha/Documents/Github/balancing_framework/spy5m_labelled_episodes_ta.pkl', 'rb') as f:
    df_ta = pickle.load(f)

In [4]:
df_ta['label'] = df['tp_0.004'][df_ta.index]

In [10]:
abs((len(df) - len(df_ta)) / len(df)) * 100

8.519796665503916

In [6]:
df_ta

,volume,vwap,open,close,high,low,transactions,label,rsi_28,stoch_k_14_3_3_28,...,delta_low_2880,macd_diff_2880,close_over_sma_2880,volatility_ratio_2880,racc_close_2880,racc_close_5760,racc_close_8640,aqr_momo_close_2880,aqr_momo_close_5760,aqr_momo_close_8640
timestamp,,,,,,,,,,,,,,,,,,,,,
2004-01-21 14:40:00-05:00,267600.0,114.4800,114.4700,114.5500,114.5600,114.36,247,1,58.737428,66.103243,...,-0.04,0.107229,1.033950,0.001030,0.001233,0.001160,0.001159,0.000017,0.000089,0.000072
2004-01-21 14:45:00-05:00,1790300.0,114.5913,114.5500,114.6700,114.6900,114.41,474,1,61.486622,77.261335,...,0.05,0.106971,1.035010,0.001029,0.001233,0.001160,0.001159,0.000024,0.000098,0.000077
2004-01-21 14:50:00-05:00,524200.0,114.7285,114.6900,114.8000,114.8300,114.63,394,1,64.168680,92.677535,...,0.22,0.109931,1.036160,0.001028,0.001233,0.001160,0.001159,0.000030,0.000103,0.000081
2004-01-21 14:55:00-05:00,165900.0,114.7873,114.7900,114.7800,114.8200,114.75,265,1,63.463562,92.306039,...,0.12,0.114183,1.035957,0.001029,0.001233,0.001160,0.001159,0.000031,0.000112,0.000079
2004-01-21 15:00:00-05:00,281000.0,114.7575,114.7600,114.7600,114.8500,114.46,235,1,62.748512,88.203792,...,-0.29,0.118442,1.035753,0.001030,0.001233,0.001160,0.001159,0.000047,0.000115,0.000078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-30 19:35:00-04:00,4929.0,500.8928,500.8900,500.8800,500.9500,500.85,71,0,38.967372,19.154907,...,-0.07,-0.157894,0.988589,0.000757,0.001044,0.000901,0.000853,0.000143,0.000083,0.000304
2024-04-30 19:40:00-04:00,10401.0,500.9938,500.9101,501.0682,501.0682,500.91,93,0,41.216741,14.264368,...,0.06,-0.147279,0.988973,0.000757,0.001044,0.000901,0.000853,0.000154,0.000079,0.000299
2024-04-30 19:45:00-04:00,3686.0,501.1517,501.1200,501.1500,501.1800,501.11,62,0,42.177301,31.505747,...,0.20,-0.135964,0.989147,0.000756,0.001044,0.000901,0.000853,0.000147,0.000080,0.000254
2024-04-30 19:50:00-04:00,1952.0,501.0709,501.1500,500.9900,501.1500,500.99,56,0,40.824141,37.827586,...,-0.12,-0.127046,0.988844,0.000756,0.001044,0.000901,0.000852,0.000141,0.000084,0.000258
2024-04-30 19:55:00-04:00,17285.0,501.2314,501.0600,501.2800,501.3100,501.06,143,0,44.189699,50.000000,...,0.07,-0.115182,0.989429,0.000756,0.001044,0.000901,0.000851,0.000158,0.000078,0.000251

In [5]:
from framework import run_measurements, viz

X = df_ta.drop(columns=['label'])
y = df_ta['label']
chunk_size = 500_000
dataset_name = 'sp500'
model_name = 'random_forest'

a,c,p = run_measurements(X, y, chunk_size, dataset_name, model_name, num_runs=1, frac_diff=False)

RUNNING ADAPTATION MEASURE

  0%|          | 0/2 [00:00<?, ?it/s][I 2024-11-21 12:07:10,540] A new study created in memory with name: no-name-2ec3ffc1-6d9f-427f-a74a-cbc083a98227

Tuning run 1 of 2

[I 2024-11-21 12:08:12,349] Trial 0 finished with value: 0.6359666666666667 and parameters: {'n_estimators': 49, 'max_depth': 4}. Best is trial 0 with value: 0.6359666666666667.

Optimization Time: 1.0548669592331863 minutes
Training run 1 of 2

 50%|█████     | 1/2 [02:04<02:04, 124.74s/it]

Run 0 Accuracy: 0.6383

[I 2024-11-21 12:09:15,943] A new study created in memory with name: no-name-f109555c-4f10-4b8f-a2c4-b78cbafd14b5

Tuning run 2 of 2

:

In [1]:
import pandas as pd
import pickle

with open('/mnt/c/Users/resha/Documents/Github/balancing_framework/spy5m_bintp_labelled.pkl', 'rb') as f:
    df_original = pickle.load(f) # ohlv + transactions + labels + bintp labels
with open('/mnt/c/Users/resha/Documents/Github/balancing_framework/spy5m_bintp004_episodes_fracdiff.pkl', 'rb') as f:
    df_fd = pickle.load(f) # fracdiffed ohlcv + transactions + labels
with open('/mnt/c/Users/resha/Documents/Github/balancing_framework/spy5m_labelled_episodes_ta.pkl', 'rb') as f:
    df_ta = pickle.load(f) # ohlcv + ~120 TA features + labels
with open('/mnt/c/Users/resha/Documents/Github/balancing_framework/spy5m_ta_fracdiff.pkl', 'rb') as f:
    df_fd_ta = pickle.load(f) # fracdiffed ohlcv + transactions + ~120 TA features + labels
# PZ algorithm has some look ahead so remove the episode labels, will be uesd only for some kind of analysis afterwards
# df = df_original.drop(columns=['episode']) 
df = df_original[["volume", "vwap", "open", "close", "high", "low", "transactions", "tp_0.004"]].rename(columns={"tp_0.004": "label"}) # 0.01 0.001
# df

In [5]:
df['close'].index += 10

TypeError: Addition/subtraction of integers and integer-arrays with DatetimeArray is no longer supported.  Instead of adding/subtracting `n`, use `n * obj.freq`

In [ ]:
for c in df_ta.columns:
    print(c)

In [4]:
df_fd['close']

timestamp
2003-10-17 14:55:00-04:00    11.485166
2003-10-17 15:00:00-04:00    11.400929
2003-10-17 15:05:00-04:00    11.501434
2003-10-17 15:10:00-04:00    11.475855
2003-10-17 15:15:00-04:00    11.560913
                               ...
2024-04-30 19:40:00-04:00    55.108495
2024-04-30 19:45:00-04:00    55.168737
2024-04-30 19:50:00-04:00    54.990292
2024-04-30 19:55:00-04:00    55.318838
2024-04-30 20:00:00-04:00    55.284322
Name: close, Length: 882450, dtype: float64

In [2]:
# to reload local packages when debugging
%load_ext autoreload
%autoreload 2

%cd /mnt/c/Users/resha/Documents/Github/balancing_framework/

from fracdiff import frac_diff_bestd, get_weights
import numpy as np
import pandas as pd

/mnt/c/Users/resha/Documents/Github/balancing_framework

In [6]:
df[['close']]

                              close
timestamp
2003-09-10 08:00:00-04:00  102.8600
2003-09-10 08:05:00-04:00  102.9000
2003-09-10 08:10:00-04:00  102.8500
2003-09-10 08:20:00-04:00  102.8000
2003-09-10 08:25:00-04:00  102.7300
...                             ...
2024-04-30 19:40:00-04:00  501.0682
2024-04-30 19:45:00-04:00  501.1500
2024-04-30 19:50:00-04:00  500.9900
2024-04-30 19:55:00-04:00  501.2800
2024-04-30 20:00:00-04:00  501.3000

[885831 rows x 1 columns]

In [11]:
df[['close']].nunique()

close    105528
dtype: int64

In [7]:
fd = frac_diff_bestd(df[['close']].copy(), type='ffd')

close

/mnt/c/Users/resha/Documents/Github/balancing_framework/fracdiff.py:189: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  series_f = series[[name]].fillna(method='ffill').dropna()

close d=0.0 stat windows =0 out of 9 p-values = [0.684670052373583, 0.9044018384381314, 0.22660968095403766, 0.8789945200031013, 0.17662044462899085, 0.620768720326262, 0.2724959171925437, 0.3292005557521428, 0.8458648161904714]

/mnt/c/Users/resha/Documents/Github/balancing_framework/fracdiff.py:189: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  series_f = series[[name]].fillna(method='ffill').dropna()

close d=0.05 stat windows =0 out of 9 p-values = [0.7091102427146666, 0.768361991258544, 0.23654020680980958, 0.6530395370610509, 0.05802430082823968, 0.5838289729570108, 0.08409450836090632, 0.16580032557613478, 0.8006321106116544]

/mnt/c/Users/resha/Documents/Github/balancing_framework/fracdiff.py:189: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  series_f = series[[name]].fillna(method='ffill').dropna()

close d=0.1 stat windows =2 out of 9 p-values = [0.32823819623074496, 0.6630974955500908, 0.07659567549304408, 0.5458678433703503, 0.008080018015451598, 0.5384238312955472, 0.02241632176750394, 0.1403670714090593, 0.6301425835108059]

/mnt/c/Users/resha/Documents/Github/balancing_framework/fracdiff.py:189: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  series_f = series[[name]].fillna(method='ffill').dropna()

close d=0.15000000000000002 stat windows =3 out of 9 p-values = [0.10592518152833458, 0.477525938641252, 0.02312323293909552, 0.43233085409307415, 0.0008521851635265352, 0.4059290174800968, 0.0018127192717300386, 0.060928795298726204, 0.34359070881998754]

/mnt/c/Users/resha/Documents/Github/balancing_framework/fracdiff.py:189: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  series_f = series[[name]].fillna(method='ffill').dropna()

close d=0.2 stat windows =4 out of 9 p-values = [0.05163271564363125, 0.2336311676979505, 0.00972550045271353, 0.15023689278192498, 3.8612540745770524e-05, 0.21400750070619434, 2.7164035338528124e-05, 0.015726747938428716, 0.1600742298084984]

/mnt/c/Users/resha/Documents/Github/balancing_framework/fracdiff.py:189: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  series_f = series[[name]].fillna(method='ffill').dropna()

close d=0.25 stat windows =6 out of 9 p-values = [0.007155320998280891, 0.07972470490682843, 0.0011311314942170291, 0.1686332629329259, 8.000171012089501e-07, 0.06518248544906437, 9.703437632743657e-08, 0.0029871989932517577, 0.04567940334523293]
close stationary with d=0.25 thresh=0.01 stat windows =6 out of 9 p-values = [0.007155320998280891, 0.07972470490682843, 0.0011311314942170291, 0.1686332629329259, 8.000171012089501e-07, 0.06518248544906437, 9.703437632743657e-08, 0.0029871989932517577, 0.04567940334523293]
changed 1 out of 1 columns; 100.0%

In [8]:
fd[0].dropna()

                               close
timestamp
2003-10-13 08:20:00-04:00  12.170765
2003-10-13 08:25:00-04:00  12.130720
2003-10-13 08:30:00-04:00  12.127966
2003-10-13 08:35:00-04:00  12.081732
2003-10-13 08:40:00-04:00  12.135423
...                              ...
2024-04-30 19:40:00-04:00  55.108495
2024-04-30 19:45:00-04:00  55.168737
2024-04-30 19:50:00-04:00  54.990292
2024-04-30 19:55:00-04:00  55.318838
2024-04-30 20:00:00-04:00  55.284322

[883028 rows x 1 columns]

In [6]:
fd

(                              close
 timestamp
 2003-09-10 08:00:00-04:00  102.8600
 2003-09-10 08:05:00-04:00  102.9000
 2003-09-10 08:10:00-04:00  102.8500
 2003-09-10 08:20:00-04:00  102.8000
 2003-09-10 08:25:00-04:00  102.7300
 ...                             ...
 2024-04-30 19:40:00-04:00  501.0682
 2024-04-30 19:45:00-04:00  501.1500
 2024-04-30 19:50:00-04:00  500.9900
 2024-04-30 19:55:00-04:00  501.2800
 2024-04-30 20:00:00-04:00  501.3000

 [885831 rows x 1 columns],
 0.0,
 {'close': (0.9500000000000001, 0.01)})